services:
  - type: web
    name: dabaa-fullstack
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      # Add other environment variables here as needed
      # - key: DATABASE_URL
      #   value: your_database_url_here
