services:
  - type: web
    name: my-fullstack-app
    env: node
    plan: free
    buildCommand: NODE_ENV=development npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: your_db_url
      - key: SESSION_SECRET
        value: your_secret
